CREATE DATABASE Ex1_3;

USE Ex1_3;

CREATE TABLE Clinica (
Id_clinica INT PRIMARY KEY IDENTITY,
endereço VARCHAR(150) NOT NULL
)

CREATE TABLE TipoPet (
Id_tipopet INT PRIMARY KEY IDENTITY,
nomeTipopet VARCHAR(50) NOT NULL
)

CREATE TABLE Raça (
Id_raça INT PRIMARY KEY IDENTITY,
nomeRaça VARCHAR(50) NOT NULL
)

CREATE TABLE Dono (
Id_dono INT PRIMARY KEY IDENTITY,
nomeDono VARCHAR(50) NOT NULL
)


CREATE TABLE Veterinario (
Id_veterinario INT PRIMARY KEY IDENTITY,
Id_clinica INT FOREIGN KEY REFERENCES Clinica (Id_clinica),
nomeVeterinario VARCHAR(50) NOT NULL
)

CREATE TABLE Pet (
Id_pet INT PRIMARY KEY IDENTITY,
Id_tipopet INT FOREIGN KEY REFERENCES TipoPet (Id_tipopet),
Id_raça INT FOREIGN KEY REFERENCES Raça (Id_raça),
Id_dono INT FOREIGN KEY REFERENCES Dono (Id_dono),
nomePet VARCHAR(50) NOT NULL,
dataNascimento DATE NOT NULL
)

CREATE TABLE Atendimento (
Id_atendimento INT PRIMARY KEY IDENTITY,
Id_clinica INT FOREIGN KEY REFERENCES Clinica (Id_clinica),
Id_pet INT FOREIGN KEY REFERENCES PET (Id_pet),
dataAtendimento DATE NOT NULL
)




